name: Generating the art work
on: push

jobs:
    artwork:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v4

            - name: All about for her
              run: echo "It's all about her"

            - name: Running the artwork
              run: ./artwork-script.sh

            - name: List all the files
              run: ls -ltra