name: Generating the art work
on:
  workflow_dispatch:
  #schedule:
  # - cron: "*/1 * * * *"
  #push

jobs:
    artwork:
      runs-on: ubuntu-latest
      steps:
        - name: All about for her
          run: echo "It's all about her"

        - name: Installation
          run: sudo apt install cowsay -y

        - name: Checking with the commands
          run: cowsay -l

        - name: Executing the command
          run: cowsay -f dragon "all self love ppl obssesed with their things up" >> dragon.txt

        - name: Creating a artifact
          uses: actions/upload-artifact@v4
          with:
            name: dragon-text-file
            path: dragon.txt

    another-artwork:
      needs: artwork
      runs-on: ubuntu-latest

      steps:
        - name: Downloading the artifact
          uses: actions/download-artifact@v4
          with:
            name: dragon-text-file

        - name: Checking files
          run: ls -ltra

        - name: Checking whether the file exists
          run: grep -i "ppl" dragon.txt

    another-artwork01:
      needs: another-artwork
      runs-on: ubuntu-latest
      steps:

        - name: Downloading the artifact
          uses: actions/download-artifact@v4
          with:
            name: dragon-text-file

        - name: Listing the files again
          run: ls -ltra

        - name: Reading the things in it
          run: cat dragon.txt

        - name: getting into the internet
          run: |
            echo "Open your windows to get the faster connection.."
            sleep 2
            echo "Getting thigns ready..."
            sleep 5
            echo "Deployed Successfully..."