name: Generating the art work
on: push

jobs:
    artwork:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v4

            - name: Installing the package
              run: sudo apt-get install cowsay -y

            - name: Listing all the animals
              run: cowsay -l

            - name: Exectung the thing CMD
              run: cowsay -f snowman "maybe today is my christmas" >> snowman.txt

            - name: Read file
              run: cat snowman.txt

            - name: Check the files
              run: ls -ltra