name: Generating the art work
on: push

jobs:
    artwork:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v4

            - name: Installing the package
              run: sudo apt-get install cowsay -y

            - name: Exectung the thing CMD
              run: cowsay -f eyes "good night stuff is boring rgt..." >> dragon.txt

            - name: Test fiel exists
              run: grep -i "eyes" dragon.txt

            - name: Read file
              run: cat dragon.txt

            - name: Check the files
              run: ls -ltra