name: Generating the art work
on: push

jobs:
    artwork:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v4

            - name: Installing the package
              run: sudo apt-get install cowsay -y

            - name: Listing all the animals
              run: cowsay -l

            - name: Exectung the thing CMD
              run: cowsay -f duck "quack quack.. ppl alert.. runs away" >> dragon.txt

            - name: Read file
              run: cat dragon.txt

            - name: Check the files
              run: ls -ltra