name: Generating the art work
on: push

jobs:
    artwork:
      runs-on: ubuntu-latest
      steps:
        - name: All about for her
          run: echo "It's all about her"

        - name: Installation
          run: sudo apt install cowsay -y

        - name: Checking with the commands
          run: cowsay -l

        - name: Executing the command
          run: cowsay -f dragon "all self love ppl obssesed with thei diary" >> dragon.txt

        - name: Wait for 10sec
          run: sleep 10

    another-artwork:
      runs-on: ubuntu-latest

      steps:
        - name: Sleep for 10 sec
          run: sleep 10

        - name: Checking files
          run: ls -ltra

        - name: Checking whether the file exists
          run: grep -i "dragon" dragon.txt

    another-artwork01:
      runs-on: ubuntu-latest
      steps:

          - name: Listing the files again
            run: ls -ltra
            
          - name: Reading the things in it
            run: cat dragon.txt

          - name: getting into the internet
            run: |
              echo "Open your windows to get the faster connection.."
              sleep 2
              echo "Getting thigns ready..."
              sleep 5
              echo "Deployed Successfully..."